### ISSUE TITLE
Help Please!

### ISSUE THREAD

**Issue by FireMS** [GDColon/GD-Save-Decoder#5]
I need help using this, I lost my password some time ago and I think it might be in my save file, but I don't know how to decode it, I used the website, and it shows me the strength. So that told me that I am able to get my password through, so I downloaded my data with the .XML option with the password included, but I don't know how to decode it. If someone can help me with this I would really appreciate it.

**Comment by GDColon** [comment]
Search for "GJA_002". It should be towards the very bottom of the file.
